### ISSUE TITLE
Cleanup the markdown files

### ISSUE THREAD

**Issue by tuxuser** [Free60Project/wiki#18]
Some markdown files are still formatted poorly (a result of the migration from MediaWiki).

Any help in cleaning up the markdown documentation would be greatly appreciated.

This involves the following:
* Fix up formatting
* Fix broken links
* Add code tags where necessary
* If content is 404 - Not found, look in the internet-archive / waybackmachine and add the content back.

**Comment by tuxuser** [comment]
## What to do

Manually look through each markdown file in `docs/` and attempt to fix the points mentioned above

## What NOT to do

Run all the files through some linting-automation. That **won't** fix the issues!

**Comment by ralf1307** [comment]
Yeah, I think I mostly resolved dead links via the wayback machine and the things I didnot manage to find or found worrying enough were put inside todo.md
