### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by NoloCreates** [Free60Project/wiki#2]
Just want to say I'm a big fan of your work and I Love that you guys are keeping this thing going.

A lot (if not all) of the Distro links lead to a 404 error. 

This one leads to a 404 error as well while trying to install Ubuntu11.10.md-

http://file.libxenon.org/free60/linux/script/ubuntu_oneiric.sh

Please don't let this project die :D

**Comment by apmorton** [comment]
direct links to files on files.libxenon.org should now work (although dns changes may take some time to propagate).
To browse the archive of files.libxenon.org you can go here: https://github.com/Free60Project/file.libxenon.org

**Comment by NoloCreates** [comment]
@apmorton thank you so much. I'm late to the scene but currently obsessed with this project. Have been trying to do some compiling in the ubuntu terminal on the 360 but have been having issues installing build-essential libcurl4-openssl-dev. Hope I can resolve this now that the links are updated. If you have any suggestions, please feel free to let me know.
