### ISSUE TITLE
Point DNS to Free60Project.github.io

### ISSUE THREAD

**Issue by halotroop2288** [Free60Project/wiki#41]
For redirects to work from the old site format to the new one, the DNS must point `free60.org/*` to `free60wiki.github.io/*` and not `github.com/free60project/wiki`

The GitHub can be linked in the top navigation bar of the wiki for quick access by adding a line to the `mkdocs.yml` file.

**Comment by tuxuser** [comment]
@apmorton Yeah that would be nice ;)

**Comment by apmorton** [comment]
We could also configure free60.org as a custom domain for this repo - nothing else is using the domain these days.

**Comment by tuxuser** [comment]
Yea let's try that

**Comment by halotroop2288** [comment]
You have to do both. If the DNS isn't pointing at GitHub.io, free60.org
will still point at GitHub.com. If you dont set it up on GitHub for a
custom domain, it won't direct traffic correctly.

**Comment by apmorton** [comment]
They are orthogonal - right now Google is hosting the domain and serving the redirect. I will configure the DNS and setup the GH pages CNAME later today.

I have already updated the redirect, free60.org should be redirecting to https://free60project.github.io/wiki/

(Including blind URL redirect)
See: https://free60.org/Attack/

We cannot however do https://free60.org/wiki/Attack/ (which I believe was the old URL scheme) AND have the index work from what I can tell.

I will

**Comment by apmorton** [comment]
DNS has been updated - pending propagation both `free60.org` and `www.free60.org` should be configured to work with GH pages (from the DNS side).

**Comment by halotroop2288** [comment]
That's perfect, thank you!
